export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'

// ADMIN
export const CURRENT_PAGE_SET = 'CURRENT_PAGE_SET'
export const ADMIN_CLIENTS_LOADED = 'ADMIN_CLIENTS_LOADED'
export const ADMIN_CLEINT_LOADED = 'ADMIN_CLEINT_LOADED'
export const ADMIN_CLIENT_SET_CURRENT_PAGE = 'ADMIN_CLIENT_SET_CURRENT_PAGE'
export const ADMIN_CLIENT_ORDERS_LOADED = 'ADMIN_CLIENT_ORDERS_LOADED'
export const ADMIN_PAGE_SET_LOADING = 'ADMIN_PAGE_SET_LOADING'
export const COURSES_LOADED = 'COURSES_LOADED'
export const COURSE_LOADED = 'COURSE_LOADED'
export const CLIENT_FOR_CHAT_LOADED = 'CLIENT_FOR_CHAT_LOADED'

// CLIENT
export const CLIENT_NOTIFICATIONS_LOADED = 'CLIENT_NOTIFICATIONS_LOADED'
export const CLIENT_ADMIN_LOADED = 'CLIENT_ADMIN_LOADED'

// MESSAGE
export const MESSAGES_LOADED = 'MESSAGES_LOADED'
export const CLIENTS_MESSAGE_NUMBERS_LOADED = 'CLIENTS_MESSAGE_NUMBERS_LOADED'
export const ADMIN_UNREAD_MESSAGES_LOADED = 'ADMIN_UNREAD_MESSAGES_LOADED'
export const CLIENT_UNREAD_MESSAGES_LOADED = 'CLIENT_UNREAD_MESSAGES_LOADED'